### ISSUE TITLE
How to run the script on all previously downloaded subtitles?

### ISSUE THREAD

**Issue by AutoGitr** [KBlixt/subcleaner#47]
I have just added the script to bazarr but if it only runs when a subtitle is grabbed, all previously downloaded subtitles will still contain their ads. How can it be made to run on all downloaded subtitles?

**Comment by KBlixt** [comment]
Python3 Subcleaner.py -r "/path/to/library"

**Comment by ovizii** [comment]
If the parameter “-r” indicates “recursively”,  I'd like to point out that `python3 subcleaner.py -h` shows no mentioning of it.

**Comment by KBlixt** [comment]
Haha yes, I was a bit conflicted about calling it library or recursive. I think -r is deeply ingrained in Linux users to mean recursive. But a user not super familiar with Linux might wonder what that word means...

So I seatled for a middle ground, long option for less experienced people and a short one for more Linux experienced ones.

In retrospect I regret calling it library mode.

**Comment by ovizii** [comment]
It was probably also due to a really stupid formatting output of my terminal. The “-r” looks like its part of the descriptive text while I kept reading the left part of the parameters over and over again looking for “-r” :-/ 

![image](https://github.com/KBlixt/subcleaner/assets/837902/e174d2ae-eb6d-4d1b-8975-7554a1ab61f0)
