### ISSUE TITLE
Many false positives

### ISSUE THREAD

**Issue by ZasX** [KBlixt/subcleaner#6]
https://github.com/KBlixt/subcleaner/blob/3f76291a98f82cfa0535b32ef32084cdad38e06d/libs/subcleaner/cleaner.py#L23

Hi!

Love the work you've done with this project. I've been using it for a few months now and I love it!

Line 23 on cleaner.py gives me a lot of false positives. If I change the 3 to a 1, it changes the false positives to warnings, so that's what I have done locally for now.

`subtitle.blocks[0].regex_matches = 1`

It would remove a lot of the first blocks of tv show subtitles that start with something like: "Previously on tv show".

**Comment by KBlixt** [comment]
Ok, yeah. That's a 2-second-clause I put in place since I've so far mostly tested against movies. And those never have legitimate subtitles in the first 2 seconds. This clause hard ban those subtitles.

Setting it to 1 seems more appropriate. Then it'll simply warn.

I'll probably change it to 1 tomorrow.

Thank you 👍

**Comment by ZasX** [comment]
Very nice, making quick work of this. I'll close the issue.
